### ISSUE TITLE
What is your code changing?

### ISSUE THREAD

**Issue by cptX** [alex-79/magento2-fix-store-information-scope#1]
Can you please explain what your code is doing? I compared your system.xml file with the default module-backend/etc/adminhtml/system.xml file and I cannot understand how your solution could help in having city and street address translated? I cannot see any difference in your code, although I didn't try your module yet. Before trying I would like to understand.

UPDATE: I think I got it, you are adding the showInStore="1" in the city and street address lines, right? And with only this change can we translate these info in every store view? I'll try it, thanks!

**Comment by alex-79** [comment]
Hi @cptX 

**showInStore** - Defines whether the section is shown on store level. Specify 1 to show the section and 0 to hide the section. (see https://experienceleague.adobe.com/en/docs/commerce-operations/configuration-guide/files/config-reference-systemxml). If this attribute is missing then the variable is global and cannot be changed for a specific store.
